version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=password
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      # Permettre l'installation de packages custom
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      # Mode debug
      - N8N_LOG_LEVEL=debug
    restart: unless-stopped
    command: >
      bash -c "
        npm install -g /tmp/plugin/*.tgz &&
        n8n start
      "
    volumes:
      - n8n_data:/home/node/.n8n
      - ./:/tmp/plugin:ro

volumes:
  n8n_data: